name: microservice-sofbank

on:
  push:
    branches: [ "main","develop" ]
  workflow_dispatch:

permissions:
  pull-requests: read
  packages: write

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

  Publish:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t msofbank:v1.0.0 -f Containerfile .

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker Image
        run: docker tag msofbank:v1.0.0 ghcr.io/${{ github.repository_owner }}/msofbank:v1.0.0

      - name: Push Docker Image to GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/msofbank:v1.0.0